const SET_PAST_ORDERS = 'SET_PAST_ORDERS';
const SET_ACTIVE_ORDERS = 'SET_ACTIVE_ORDERS';
const CLEAR_ORDERS = 'CLEAR_ORDERS';
const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';

export {SET_PAST_ORDERS, SET_ACTIVE_ORDERS, CLEAR_ORDERS, SET_ORDER_DETAILS};
