const SET_PAST_ORDERS = 'SET_PAST_ORDERS';
const SET_ACTIVE_ORDERS = 'SET_ACTIVE_ORDERS';
const CLEAR_ORDERS = 'CLEAR_ORDERS';
const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';
const SET_ALTERNATIVE_STORES = 'SET_ALTERNATIVE_STORES';
const CLEAR_ALTERNATIVE_STORES = 'CLEAR_ALTERNATIVE_STORES';

export {
  SET_PAST_ORDERS,
  SET_ACTIVE_ORDERS,
  CLEAR_ORDERS,
  SET_ORDER_DETAILS,
  SET_ALTERNATIVE_STORES,
  CLEAR_ALTERNATIVE_STORES,
};
