const SET_FILTERS = 'SET_FILTERS';
const SET_SUBCATEGORY_PRODUCTS = 'SET_SUBCATEGORY_PRODUCTS';
const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
const SET_STORE_DETAILS = 'SET_STORE_DETAILS';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
const SET_CATEGORIES = 'SET_CATEGORIES';
const SET_LOADING_PRODUCT = 'SET_LOADING_PRODUCT';
const SET_STORE_ACTIVE_ORDERS = 'SET_STORE_ACTIVE_ORDERS';
const SET_STORE_PAST_ORDERS = 'SET_STORE_PAST_ORDERS';
const CLEAR_STORE_ORDERS = 'CLEAR_STORE_ORDERS';
const SET_STORE_SEARCH_PRODUCTS = 'SET_STORE_SEARCH_PRODUCTS';
const CLEAR_STORE_SEARCH_PRODUCTS = 'CLEAR_STORE_SEARCH_PRODUCTS';

export {
  SET_FILTERS,
  SET_SUBCATEGORY_PRODUCTS,
  SET_CATEGORY_PRODUCTS,
  SET_STORE_DETAILS,
  ADD_PRODUCTS,
  CLEAR_PRODUCTS,
  SET_CATEGORIES,
  SET_LOADING_PRODUCT,
  SET_STORE_ACTIVE_ORDERS,
  SET_STORE_PAST_ORDERS,
  CLEAR_STORE_ORDERS,
  SET_STORE_SEARCH_PRODUCTS,
  CLEAR_STORE_SEARCH_PRODUCTS,
};
