const SET_FILTERS = 'SET_FILTERS';
const SET_SUBCATEGORY_PRODUCTS = 'SET_SUBCATEGORY_PRODUCTS';
const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
const SET_STORE_DETAILS = 'SET_STORE_DETAILS';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
const SET_CATEGORIES = 'SET_CATEGORIES';

export {
  SET_FILTERS,
  SET_SUBCATEGORY_PRODUCTS,
  SET_CATEGORY_PRODUCTS,
  SET_STORE_DETAILS,
  ADD_PRODUCTS,
  CLEAR_PRODUCTS,
  SET_CATEGORIES,
};
