const SET_LOADING = 'SET_LOADING';
const SET_TOKEN = 'SET_TOKEN';
const LOGOUT_USER = 'LOGOUT_USER';
const SET_DISABLE_LOADING = 'SET_DISABLE_LOADING';
const SET_NO_INTERNET = 'SET_NO_INTERNET';
const SET_API_ERROR = 'SET_API_ERROR';
const SET_NOTIFICATION_PAYLOAD = 'SET_NOTIFICATION_PAYLOAD';

export {
  SET_LOADING,
  SET_TOKEN,
  LOGOUT_USER,
  SET_DISABLE_LOADING,
  SET_NO_INTERNET,
  SET_API_ERROR,
  SET_NOTIFICATION_PAYLOAD,
};
