const SET_LOADING = 'SET_LOADING';
const SET_TOKEN = 'SET_TOKEN';
const LOGOUT_USER = 'LOGOUT_USER';
const SET_DISABLE_LOADING = 'SET_DISABLE_LOADING';

export {SET_LOADING, SET_TOKEN, LOGOUT_USER, SET_DISABLE_LOADING};
