const SET_CART_QUANTITY = 'SET_CART_QUANTITY';
const SET_USER_DETAILS = 'SET_USER_DETAILS';
const APPEND_STORES = 'APPEND_STORES';
const CLEAR_STORES = 'CLEAR_STORES';

export {SET_USER_DETAILS, SET_CART_QUANTITY, APPEND_STORES, CLEAR_STORES};
