const SET_USER_DETAILS = 'SET_USER_DETAILS';
const APPEND_STORES = 'APPEND_STORES';
const CLEAR_STORES = 'CLEAR_STORES';
const APPEND_SEARCHED_STORES = 'APPEND_SEARCHED_STORES';
const CLEAR_SEARCHED_STORES = 'CLEAR_SEARCHED_STORES';
const APPEND_STORE_PRODUCTS = 'APPENT_STORE_PRODUCTS';
const CLEAR_STORE_PRODUCTS = 'CLEAR_STORE_PRODUCTS';
const SELECT_STORE = 'SELECT_STORE';
const APPEND_USER_DETAILS = 'APPEND_USER_DETAILS';
const APPEND_CURRENT_ORDERS = 'APPEND_CURRENT_ORDERS';
const REMOVE_FROM_CURRENT_ORDERS = 'REMOVE_FROM_CURRENT_ORDERS';

export {
  SET_USER_DETAILS,
  APPEND_STORES,
  CLEAR_STORES,
  APPEND_SEARCHED_STORES,
  CLEAR_SEARCHED_STORES,
  APPEND_STORE_PRODUCTS,
  CLEAR_STORE_PRODUCTS,
  SELECT_STORE,
  APPEND_USER_DETAILS,
  APPEND_CURRENT_ORDERS,
  REMOVE_FROM_CURRENT_ORDERS,
};
