export const Urls = {
  kiranaKartWebUrl: 'https://www.kiranakart.app',
  privacyUrl: 'https://www.kiranakart.app/Privacy_Policy-KiranaKart.docx',
  termsUrl: 'https://www.kiranakart.app/KiranaKart%20T_and_C.docx',

  sendOtp: '/organisation/user/send-sms-otp',
  verifyOtp: '/organisation/user/verify-otp',
  upload: '/common/attachment/upload',
  addUpdateAddress: '/organisation/user/add-update-user-address',
  getAddresses: '/organisation/user/get-user-addresses',
  deleteAddress: '/organisation/user/delete-user-address',
  getUserDetails: '/organisation/user/get-user-details',
  getStores: '/offering/store/get-stores-by-location',
  getStoreDetails: '/offering/store/get-store-details-and-products',
  getProductsByCategory: '/offering/store/get-store-products-by-category-id',
  searchStoreProducts: '/offering/store/search-store-products',
  getStoreCategories: '/offering/category/get-store-categories',
  searchProductInStores: '/offering/product/search-product-and-get-stores',
  addUpdateItemToCart: '/commerce/cart/add-update-item-to-cart',
  getCart: '/commerce/cart/get-cart',
  sendOtpToChangeNumber: '/organisation/user/send-otp-to-change-number',
  verifyOtpChangeNumber: '/organisation/user/verify-otp-change-number',
  createOrder: 'commerce/order/create-order',
  updateUserDetails: '/organisation/user/update-user-details',
  placeOrder: 'commerce/order/place-order',
  getOrders: 'commerce/order/get-consumer-order-history',
  getOrderDetails: '/commerce/order/get-order-details',
  cancelOrder: '/commerce/order/cancel-order',
  getStoresByOrderId: '/offering/store/get-stores-by-order-id',
  repeatOrderToCart: '/commerce/cart/repeat-order-to-cart',

  googleGeocode: 'https://maps.googleapis.com/maps/api/geocode/json',
};

// Postman Collection : https://www.getpostman.com/collections/ded852ca8b6569f7f386
