export const Strings = {
  supportEmail: 'support@kiranakart.com',

  introTitle1: 'Groceries delivered instantly',
  introTitle2: 'Shop from your trusted Kiranas',
  introTitle3: 'No phone calls, no frustration',
  introSubText1:
    "We've partnered with WeFast to do rapid deliveries from local Kiranas. In fact, most of our orders are delivered in an hour.",
  introSubText2:
    "We're working with Kirana stores across Mumbai to give you a high-quality shopping experience.",
  introSubText3:
    "Kiranakart gives you a convenient way to browse through a store's inventory and place orders with a single tap.",

  hinglish: 'Hinglish ',
  hinglishDesc: '(Hindi in English)',
  english: 'English',

  next: 'Next',
  continue: 'Continue',
  save: 'Save',
  invalidNumber: 'Invalid Number',
  verify: 'Verify',
  selectFrom: 'Select From',
  skip: 'Skip',
  camera: 'Camera',
  gallery: 'Gallery',
  shareStore: 'Share Store',
  bankName: 'Bank Name',
  accName: 'Account Name',
  accNumber: 'Account Number',
  ifsc: 'IFSC',
  invalidAccNumber: 'Invalid Account Number',
  invalidIFSC: 'Invalid IFSC Code',
  productName: 'Product Name',
  brand: 'Brand',
  selectCategory: 'Select Category ',
  selectSubCategory: 'Select Subcategory ',
  enterPrice: 'Enter Price',
  selectUnit: 'Select Unit',
  enterQuantity: 'Enter Quantity',
  add: 'Add',
  inStore: 'In Store',
  searchSubCategory: 'Search subcategory',
  ok: 'Ok',
  change: 'Change',
  no: 'No',
  iamDone: 'I am Done',
  branded: 'Branded',
  unbranded: 'Unbranded',
  editDetails: 'Edit Details',
  editProfile: 'Edit Profile',
  loading: 'Loading...',
  whatsapp: 'WhatsApp',
  moreOptions: 'More Options',
  done: 'Done',
  notNow: 'Not now',
  currentLocation: 'Current Location',
  edit: 'Edit',
  delete: 'Delete',
  view: 'View',
  more: 'more',
  plusAdd: '+ Add',
  addToCart: 'Add to Cart',
  saveAndProceed: 'Save and Proceed',
  cancel: 'Cancel',
  getOtp: 'Get OTP',
  filter: 'Filter',
  clearAll: 'Clear All',
  apply: 'Apply',

  chooseLanguage: 'Choose Language',
  loginTitle: 'Enter your mobile number',
  loginSubTitle: 'We will send you a verification code on this number',
  verifyOtp: 'Verify mobile number',
  otpSent: 'Enter the OTP sent to +91 ',
  preResend: "I didn't recieve the code ",
  resend: 'Resend Code',
  resendWait: 'Resend Code in ',
  location: 'Location',
  address: 'Address',
  home: 'Home',
  work: 'Work',
  other: 'Other',
  addAddress: 'Add Address',
  pay: 'Pay',
  fullName: 'Full Name',

  accepting: 'By continuing, I accept ',
  terms: 'terms of service',
  and: ' and ',
  privacy: 'privacy policy',

  mobileNumber: 'Mobile Number',
  storeName: 'Store Name',
  storeLocation: 'Store location',
  openTime: 'Open Time',
  closeTime: 'Close Time',
  currency: '\u20B9',

  myOrders: 'My Orders',
  addresses: 'Addresses',
  referFriends: 'Refer Friends',
  settings: 'Account Settings',
  support: 'Customer Support',
  termsConditions: 'Terms & Conditions',
  privacyPolicy: 'Privacy Policy',
  logout: 'Logout',

  shop: 'Shop',
  explore: 'Explore',
  orders: 'Orders',

  referal: 'Referral Code',

  continuePhoneNumber: 'Continue with Phone Number',
  drawerFreeDeliverySub:
    'Refer friends and get free deliveries. It’s a Win-Win!',
  referHeadline: 'Refer you friends & Get Free Delivery',
  referSub:
    'Invite your friends and get 3 free delivery and more surprise offers.',
  gotReferal: 'Got a referral code? Redeem it here.',
  getFreeDelivery: 'Get free delivery',
  enterReferal: 'Please enter your referal code and get 3 free deliveries.',
  referSuccessTitle: 'Congratulations you got 3 free deliveries',
  referSuccessSub:
    'Do you want more? Share your referral code with your friends now.',
  locationOff: 'Device Location is off',
  locationOffSub:
    'Turning on device Location will ensure accurate and hassle free delivery',
  locationOffHome:
    'Please turn on your device location to ensure hassle free experience',
  turnOn: 'Turn on',
  ownStore: 'Own a kirana store?',
  joinAsShop: 'Join as a shopkeeper',
  searchDeliveryLocation: 'Search Delivery Location',
  usingGPS: 'Using GPS',
  searchLocationPlaceHolder: 'Search for area, street name...',
  addressLine: 'House/Flat/ Block No.',
  landmark: 'Landmark',
  saveAddressAs: 'Save your address as',
  noSavedAddress: 'You have no saved addresses',
  searchProduct: 'Search Product',
  nearbyStores: 'Nearby Stores',
  completeAccSetup: 'Complete account setup',
  allItems: 'All Items',
  turnOnLocation: 'Turn on Device Location',
  searchManually: 'Seach Location Manually',
  useCurrentLocation: 'Use Current Location',
  savedAddresses: 'Saved Addresses',
  found: 'Found',
  storesMatching: 'stores matching',
  itemsMatching: 'items matching',
  noSearchResults: 'Sorry! We can’t find any product matching your search.',
  locationUnavaible: 'Location Unavailable',
  deleteAddress: 'Delete Address',
  confirmDeleteAddress: 'Are you sure you want to the address',
  confirmDeleteAddress2: 'from your address list?',
  yesDelete: 'Yes, Delete',
  referScreenHeadline: 'Refer a friend, get free deliveries!',
  referScreenSub:
    "When your friends use your referral code while signing up, you'll both get 3 free deliveries! It's a win-win :)",
  seeInvites: 'See your referrals',
  yourInvites: 'Your Invites',
  rewarded: 'Rewarded',
  on: 'on',
  yourNext: 'Your next',
  deliveriesWillFree: 'deliveries will be free!',
  phoneNumber: 'Phone Number',
  whatsappHelp: 'Connect with a support representative',
  email: 'Email',
  customerSupport: 'Customer Support',
  helpText: "We're here to help you 24x7",
  accountSetupNameHeadline: 'Tell us your name',
  accountSetup: 'Account Setup',
  accountSetting: 'Account Setting',
  currentNumber: 'Current Number',
  enterNewNumber: 'Please enter your new mobile number',
  changeNumber: 'Change Mobile Number',
  verifyNumber: 'Verify your phone number',
  groceryCategories: 'Grocery Categories',
  paid: 'Paid',
  trackOrder: 'Track Order',
  storeClosed: 'Store Closed',
  orderNowGetAt: 'Order Now, Get it at ',
  viewAll: 'View All',
  commonSearches: 'Common Searches',
  viewStore: 'View Entire Store',
  homeStoresEmpty: 'Sorry! We can’t find any stores in your location',
  changeLocation: 'Change Location',
  storeSearchEmpty: "Sorry! We can't find any stores matching ",
  noProductFound: 'Sorry! We can’t find any product matching your search.',
  otpError: 'Please enter a valid 4 digit OTP',
  confirmOrder: 'Confirm Order',
  cartInstructionsPlaceholder: 'Any Instructions? Eg: Don’t ring the doorbell',
  estimatedDeliveryTime: 'Estimated Time of Delivery is ',
  paymentDetails: 'Payment Details',
  youSaved: 'You saved',
  onThisBill: 'on this bill',
  subTotal: 'Sub Total',
  deliveryCharge: 'Delivery charge',
  grandTotal: 'Grand Total',
  addAddressToProceed: 'Add an address to proceed',
  pleaseAddAddress: 'Please add your delivery address.',
  selectDeliveryAddress: 'Select delivery address',
  addNewAddress: '+ Add new address',
  deliverTo: 'Deliver to:',
  plusAddMore: '+ Add more',
  overWeightCartText: 'Max. weight limit is 10 kg. Reduce items to proceed.',
  cartNotDeliverable: 'Delivery address not servicable, please add new address',
  cartEmptyTitle: 'All your grocery needs are a click away',
  cartEmptySubTitle: 'Your cart is empty. Add items from nearby stores. ',
  addProducts: 'Add products',
  replaceHeading: 'Replace cart item?',
  replaceDesc1: 'Your cart contains items from ',
  replaceDesc2: '. Do you want to discard the selection and add items from ',
  yesDiscard: 'Yes, Discard',
  paymentSuccess: 'Payment Success',
  paymentSuccessSub:
    'Your order has been placed successfully and is being processed',
  paymentFailed: 'Payment Failed',
  paymentFailedSub:
    'Looks like something went wrong while processing your request.',
};
