export const Strings = {
  introTitle1: 'Sell online, multiply your revenue',
  introTitle2: 'No delivery hassle',
  introTitle3: 'Manage your orders easily',
  introSubText1:
    'By selling online with KiranaKart, your store gains access to thousands of new customers across Mumbai!',
  introSubText2:
    "We do the deliveries for you! We've partnered with WeFast to make sure your customers get deliveries instantly.",
  introSubText3:
    'Our app helps you track your orders and sales automatically. No more pen and paper frustration.',

  hinglish: 'Hinglish ',
  hinglishDesc: '(Hindi in English)',
  english: 'English',

  next: 'Next',
  continue: 'Continue',
  save: 'Save',
  invalidNumber: 'Invalid Number',
  verify: 'Verify Now',
  selectFrom: 'Select From',
  skip: 'Skip',
  camera: 'Camera',
  gallery: 'Gallery',
  shareStore: 'Share Store',
  bankName: 'Bank Name',
  accName: 'Account Name',
  accNumber: 'Account Number',
  ifsc: 'IFSC',
  invalidAccNumber: 'Invalid Account Number',
  invalidIFSC: 'Invalid IFSC Code',
  productName: 'Product Name',
  brand: 'Brand',
  selectCategory: 'Select Category ',
  selectSubCategory: 'Select Subcategory ',
  enterPrice: 'Enter Price',
  selectUnit: 'Select Unit',
  enterQuantity: 'Enter Quantity',
  add: 'Add',
  inStore: 'In Store',
  searchSubCategory: 'Search subcategory',
  ok: 'Ok',
  change: 'Change',
  no: 'No',
  iamDone: 'I am Done',
  branded: 'Branded',
  unbranded: 'Unbranded',
  editDetails: 'Edit Details',
  editProfile: 'Edit Profile',
  shopkeeperName: 'Shopkeeper Name',
  loading: 'Loading...',

  chooseLanguage: 'Choose Language',
  loginTitle: 'Enter your mobile number',
  loginSubTitle: 'We will send you a verification code on this number',
  verifyOtp: 'Verify mobile number',
  otpSent: 'Enter the OTP sent to +91 ',
  preResend: "I didn't recieve the code ",
  resend: 'Resend Code',
  resendWait: 'Resend Code in ',

  accepting: 'By continuing, I accept ',
  terms: 'terms of service',
  and: ' and ',
  privacy: 'privacy policy',
  storeDetails: 'Store Details',
  storeDetailsSub: 'Kindly enter your Store detail',
  addPhoto: 'Add a Photo',
  addProfilePhoto: 'Add Profile Photo',
  addPhotoSub: 'please add your profile photo',
  photoAdded: 'Profile photo added',
  changePhoto: 'Change Photo',
  youOffline: 'You are Offline',
  youOnline: 'You are Online',
  youOfflineSub: 'Go online to start accepting orders',
  completeDetails: 'Complete your details',
  completeDetailsSub:
    'Before you accepting the order you need to finish following tasks',
  addBank: 'Add your Bank Account details',
  addBankSub: 'Please add account details for store approval  ',
  addBankDetails: 'Add Bank Details',
  editBankDetails: 'Edit Bank Details',
  productOnboard: 'Start your product onboarding',
  addProductsToStore: 'Please add products available in the store',
  addProduct: 'Add Product',
  shareWhatsapp: 'Share on Whatsapp',
  shareWhatsappSub: 'Share your store details with 5 contacts on whatsApp',
  shareButton: 'Share',
  bankDetails: 'Bank Details',
  bankDetailsDesc:
    'We need your bank details to process the payments for customer orders fulfilled by you',
  addProducts: 'Add Products',
  editProducts: 'Edit Products',
  createProduct: 'Create Product',
  addProductImage: 'Add Product Image (upto 2)',
  addedToSection: 'added in this section',
  addedSoFar: 'added so far',
  products: 'Products',
  searchEmpty: "Let us help you find what you're looking for.",
  invalidTime: 'Invalid Closing Time/Opening Time.',
  complete: 'Complete',
  continueAddingProducts: 'Continue adding more products',
  storeCreatedTitle: 'Store successfully created!',
  storeCreatedSub:
    'Your store has been sucessfully created please start listing your products',
  storeRejectedTitle: 'Store Rejected',
  storeRejectedSub:
    'Kindly review the details provided to us. Certain guidelines have not been fulfilled',
  storePendingTitle: 'Store Request Pending',
  storePendingSub: 'Pending request sub',
  storeDeactivatedTitle: 'Store Deactivated',
  storeDeactivatedSub: 'Deactivated sub',
  tryAgain: 'Try again',
  goOnline: 'Go Online',
  cannotGoOnline:
    'You cannot go online before filling all the necessary details.',
  readyToAccept: 'You are all set for accepting orders',
  youAdded: 'You added',
  soFar: 'so far',
  unbrandedProducts: 'Unbranded Products',
  searchStore: 'Search Store Location',
  searchLocationPlaceHolder: 'Search for area, street name...',
  currentLocation: 'Current Location',
  usingGPS: 'Using GPS',
  changeLocation: 'Change Location',
  confirmLocation: 'Confirm Location',
  unknown: 'Unknown',
  pricesInfo:
    'All prices are set to MRP automatically. You can change them to a lower price if you want.',
  productInventory: 'Product Inventory',
  productInventorySub:
    "Are you sure that you haven't missed any product available in your store?",
  productBrandType: 'Product Brand Type',
  yourOwn: 'Your own',
  onlineStore: 'Online Store',
  welcomeMessage:
    'Welcome to the Kirana Kart,\nManage and track your Store online orders',
  shareSubText: 'Share your store details with friends & Contacts on whatsApp',
  shopkeeperPhoto: 'Shopkeeper Photo',

  mobileNumber: 'Mobile Number',
  storeName: 'Store Name',
  storeLocation: 'Store location',
  openTime: 'Open Time',
  closeTime: 'Close Time',
  currency: '\u20B9',

  helpSupport: 'Help & Support',
  sales: 'Sales Report',
  changeLanguage: 'Change Language',
  videoGuide: 'Video Guide',
  termsConditions: 'Terms & Conditions',
  logout: 'Logout',

  orders: 'Orders',
  inventory: 'Inventory',
  myShop: 'My Shop',

  new: 'New',
  preparing: 'Preparing',
  dispatched: 'Dispatched',
  completed: 'Completed',

  noOrderTitle: 'You don’t have any orders yet ',
  noOrderSubtitle:
    'Update your inventory regularly so that customers always find what they need',
};
