export const Strings = {
  introTitle1: 'Groceries delivered instantly',
  introTitle2: 'Shop from your trusted Kiranas',
  introTitle3: 'No phone calls, no frustration',
  introSubText1:
    "We've partnered with WeFast to do rapid deliveries from local Kiranas. In fact, most of our orders are delivered in an hour.",
  introSubText2:
    "We're working with Kirana stores across Mumbai to give you a high-quality shopping experience.",
  introSubText3:
    "Kiranakart gives you a convenient way to browse through a store's inventory and place orders with a single tap.",

  hinglish: 'Hinglish ',
  hinglishDesc: '(Hindi in English)',
  english: 'English',

  next: 'Next',
  continue: 'Continue',
  save: 'Save',
  invalidNumber: 'Invalid Number',
  verify: 'Verify Now',
  selectFrom: 'Select From',
  skip: 'Skip',
  camera: 'Camera',
  gallery: 'Gallery',
  shareStore: 'Share Store',
  bankName: 'Bank Name',
  accName: 'Account Name',
  accNumber: 'Account Number',
  ifsc: 'IFSC',
  invalidAccNumber: 'Invalid Account Number',
  invalidIFSC: 'Invalid IFSC Code',
  productName: 'Product Name',
  brand: 'Brand',
  selectCategory: 'Select Category ',
  selectSubCategory: 'Select Subcategory ',
  enterPrice: 'Enter Price',
  selectUnit: 'Select Unit',
  enterQuantity: 'Enter Quantity',
  add: 'Add',
  inStore: 'In Store',
  searchSubCategory: 'Search subcategory',
  ok: 'Ok',
  change: 'Change',
  no: 'No',
  iamDone: 'I am Done',
  branded: 'Branded',
  unbranded: 'Unbranded',
  editDetails: 'Edit Details',
  editProfile: 'Edit Profile',
  loading: 'Loading...',
  whatsapp: 'Whatsapp',
  moreOptions: 'More Options',
  done: 'Done',
  notNow: 'Not now',
  currentLocation: 'Current Location',
  edit: 'Edit',
  delete: 'Delete',
  view: 'View',
  more: 'more',
  plusAdd: '+ Add',
  addToCart: 'Add to Cart',

  chooseLanguage: 'Choose Language',
  loginTitle: 'Enter your mobile number',
  loginSubTitle: 'We will send you a verification code on this number',
  verifyOtp: 'Verify mobile number',
  otpSent: 'Enter the OTP sent to +91 ',
  preResend: "I didn't recieve the code ",
  resend: 'Resend Code',
  resendWait: 'Resend Code in ',
  location: 'Location',
  address: 'Address',
  home: 'Home',
  work: 'Work',
  other: 'Other',
  addAddress: 'Add Address',

  accepting: 'By continuing, I accept ',
  terms: 'terms of service',
  and: ' and ',
  privacy: 'privacy policy',

  mobileNumber: 'Mobile Number',
  storeName: 'Store Name',
  storeLocation: 'Store location',
  openTime: 'Open Time',
  closeTime: 'Close Time',
  currency: '\u20B9',

  myOrders: 'My Orders',
  addresses: 'Addresses',
  referFriends: 'Refer Friends',
  settings: 'Account Settings',
  support: 'Customer Support',
  termsConditions: 'Terms & Conditions',
  privacyPolicy: 'Privacy Policy',
  logout: 'Logout',

  orders: 'Orders',
  inventory: 'Inventory',
  referal: 'Referral Code',

  continuePhoneNumber: 'Continue with Phone Number',
  drawerFreeDeliverySub:
    'Refer friends and get free deliveries. It’s a Win-Win!',
  referHeadline: 'Refer you friends & Get Free Delivery',
  referSub:
    'Invite your friends and get 3 free delivery and more surprise offers.',
  gotReferal: 'Got a referral code? Redeem it here.',
  getFreeDelivery: 'Get free delivery',
  enterReferal: 'Please enter your referal code and get 3 free deliveries.',
  referSuccessTitle: 'Congratulations you got 3 free deliveries',
  referSuccessSub:
    'Do you want more? Share your referral code with your friends now.',
  locationOff: 'Device Location is off',
  locationOffSub:
    'Turning on device Location will ensure accurate and hassle free delivery',
  locationOffHome:
    'Please turn on your device location to ensure hassle free experience',
  turnOn: 'Turn on',
  ownStore: 'Own a kirana store?',
  joinAsShop: 'Join as a shopkeeper',
  searchDeliveryLocation: 'Search Delivery Location',
  usingGPS: 'Using GPS',
  searchLocationPlaceHolder: 'Search for area, street name...',
  addressLine: 'House/Flat/ Block No.',
  landmark: 'Landmark',
  saveAddressAs: 'Save your address as',
  noSavedAddress: 'You don’t have any saved address to show',
  searchProduct: 'Search Product',
  nearbyStores: 'Nearby Stores',
  completeAccSetup: 'Complete account setup',
  allItems: 'All Items',
  turnOnLocation: 'Turn on Device Location',
  searchManually: 'Seach Location Manually',
  useCurrentLocation: 'Use Current Location',
  savedAddresses: 'Saved Addresses',
  found: 'Found',
  storesMatching: 'stores matching',
  itemsMatching: 'items matching',
  noSearchResults: 'Sorry! We can’t find any product matching your search.',
  locationUnavaible: 'Location Unavaible',
};
